## Obtendo conjunto de dados

In [1]:
import pandas as pd
exemplo1 = pd.read_csv('output.csv', sep=',')

In [2]:
exemplo1

a  b
0  1  2
1  3  4
2  5  6

In [3]:
!pip install -q scikit-learn
from sklearn.datasets import load_iris

In [4]:
data = load_iris()

In [5]:
iris_df = pd.DataFrame(data.data, columns=data.feature_names)
iris_df['encoded_target'] = data.target

In [6]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

## Lidando com Dados Nulos e Corrompidos

In [ ]:
iris_df.iloc[0, 0] = None
iris_df.iloc[0, 1] = None
iris_df.iloc[0, 2] = None
iris_df.iloc[1, 0] = None
iris_df.iloc[4, 3] = None
iris_df.iloc[149, 2] = None
iris_df.iloc[3, 3] = -9999
iris_df.iloc[3, 0] = "cancanqnqwe"



/tmp/ipykernel_18468/125148158.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'cancanqnqwe' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  iris_df.iloc[3, 0] = "cancanqnqwe"


In [8]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 NaN               NaN                NaN      2.000000e-01   
1                 NaN               3.0                1.4      2.000000e-01   
2                 4.7               3.2                1.3      2.000000e-01   
3         cancanqnqwe               3.1                1.5     -1.000000e+12   
4                 5.0               3.6                1.4               NaN   
..                ...               ...                ...               ...   
145               6.7               3.0                5.2      2.300000e+00   
146               6.3               2.5                5.0      1.900000e+00   
147               6.5               3.0                5.2      2.000000e+00   
148               6.2               3.4                5.4      2.300000e+00   
149               5.9               3.0                NaN      1.800000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

In [9]:
iris_df.isna()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 True              True               True             False   
1                 True             False              False             False   
2                False             False              False             False   
3                False             False              False             False   
4                False             False              False              True   
..                 ...               ...                ...               ...   
145              False             False              False             False   
146              False             False              False             False   
147              False             False              False             False   
148              False             False              False             False   
149              False             False               True             False   

     encoded_target  
0             False  
1             False  
2             False  
3             False  
4             False  
..              ...  
145           False  
146           False  
147           False  
148           False  
149           False  

[150 rows x 5 columns]

In [10]:
iris_df[iris_df.isna().any(axis=1)]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 NaN               NaN                NaN               0.2   
1                 NaN               3.0                1.4               0.2   
4                 5.0               3.6                1.4               NaN   
149               5.9               3.0                NaN               1.8   

     encoded_target  
0                 0  
1                 0  
4                 0  
149               2

In [11]:
iris_df_rem = iris_df.dropna()

In [12]:
iris_df_rem[iris_df_rem.isna().any(axis=1)]

Empty DataFrame
Columns: [sepal length (cm), sepal width (cm), petal length (cm), petal width (cm), encoded_target]
Index: []

In [13]:
iris_df_zero = iris_df.fillna(0)
iris_df_zero

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                   0               0.0                0.0      2.000000e-01   
1                   0               3.0                1.4      2.000000e-01   
2                 4.7               3.2                1.3      2.000000e-01   
3         cancanqnqwe               3.1                1.5     -1.000000e+12   
4                 5.0               3.6                1.4      0.000000e+00   
..                ...               ...                ...               ...   
145               6.7               3.0                5.2      2.300000e+00   
146               6.3               2.5                5.0      1.900000e+00   
147               6.5               3.0                5.2      2.000000e+00   
148               6.2               3.4                5.4      2.300000e+00   
149               5.9               3.0                0.0      1.800000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

In [14]:
iris_df_valores_impossiveis = iris_df.fillna(-999)
iris_df_valores_impossiveis

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                -999            -999.0             -999.0      2.000000e-01   
1                -999               3.0                1.4      2.000000e-01   
2                 4.7               3.2                1.3      2.000000e-01   
3         cancanqnqwe               3.1                1.5     -1.000000e+12   
4                 5.0               3.6                1.4     -9.990000e+02   
..                ...               ...                ...               ...   
145               6.7               3.0                5.2      2.300000e+00   
146               6.3               2.5                5.0      1.900000e+00   
147               6.5               3.0                5.2      2.000000e+00   
148               6.2               3.4                5.4      2.300000e+00   
149               5.9               3.0             -999.0      1.800000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

In [15]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  148 non-null    object 
 1   sepal width (cm)   149 non-null    float64
 2   petal length (cm)  148 non-null    float64
 3   petal width (cm)   149 non-null    float64
 4   encoded_target     150 non-null    int64  
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB


In [16]:
iris_df['sepal length (cm)'].unique()

array([nan, 4.7, 'cancanqnqwe', 5.0, 5.4, 4.6, 4.4, 4.9, 4.8, 4.3, 5.8,
       5.7, 5.1, 5.2, 5.5, 4.5, 5.3, 7.0, 6.4, 6.9, 6.5, 6.3, 6.6, 5.9,
       6.0, 6.1, 5.6, 6.7, 6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9],
      dtype=object)

In [17]:
iris_df = iris_df[iris_df['sepal length (cm)'] != 'cancanqnqwe'].reset_index(drop=True)

In [18]:
iris_df['sepal length (cm)'].unique()

array([nan, 4.7, 5.0, 5.4, 4.6, 4.4, 4.9, 4.8, 4.3, 5.8, 5.7, 5.1, 5.2,
       5.5, 4.5, 5.3, 7.0, 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6.0, 6.1, 5.6,
       6.7, 6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9], dtype=object)

In [23]:
iris_df.iloc[3, 3] = -9999

In [24]:
#identificando pontos fora da curva
iris_df['petal width (cm)'].unique()

array([ 2.000e-01, -9.999e+03,  4.000e-01,  3.000e-01,  1.000e-01,
        5.000e-01,  6.000e-01,  1.400e+00,  1.500e+00,  1.300e+00,
        1.600e+00,  1.000e+00,  1.100e+00,  1.800e+00,  1.200e+00,
        1.700e+00,  2.500e+00,  1.900e+00,  2.100e+00,  2.200e+00,
        2.000e+00,  2.400e+00,  2.300e+00])

In [26]:
iris_df.iloc[3, 3] = None
iris_df['petal width (cm)'].unique()

array([0.2, nan, 0.4, 0.3, 0.1, 0.5, 0.6, 1.4, 1.5, 1.3, 1.6, 1. , 1.1,
       1.8, 1.2, 1.7, 2.5, 1.9, 2.1, 2.2, 2. , 2.4, 2.3])

## Regularização de Dados

In [27]:
import numpy as np
iris_df['artificial'] = np.random.uniform(100, 1000, iris_df.shape[0]).round(2)

In [28]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 NaN               NaN                NaN               0.2   
1                 NaN               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 5.0               3.6                1.4               NaN   
4                 5.4               3.9                1.7               0.4   
..                ...               ...                ...               ...   
144               6.7               3.0                5.2               2.3   
145               6.3               2.5                5.0               1.9   
146               6.5               3.0                5.2               2.0   
147               6.2               3.4                5.4               2.3   
148               5.9               3.0                NaN               1.8   

     encoded_target  artificial  
0                 0      453.15  
1                 0      485.43  
2                 0      648.93  
3                 0      675.82  
4                 0      765.60  
..              ...         ...  
144               2      574.90  
145               2      929.01  
146               2      558.77  
147               2      706.49  
148               2      994.81  

[149 rows x 6 columns]

In [29]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print(scaler.fit(iris_df))
novo_iris_df = scaler.transform(iris_df)

MinMaxScaler()


In [30]:
novo_iris_df = pd.DataFrame(novo_iris_df, columns=iris_df.columns).round(2)

In [31]:
novo_iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  NaN               NaN                NaN              0.04   
1                  NaN              0.42               0.07              0.04   
2                 0.11              0.50               0.05              0.04   
3                 0.19              0.67               0.07               NaN   
4                 0.31              0.79               0.12              0.12   
..                 ...               ...                ...               ...   
144               0.67              0.42               0.71              0.92   
145               0.56              0.21               0.68              0.75   
146               0.61              0.42               0.71              0.79   
147               0.53              0.58               0.75              0.92   
148               0.44              0.42                NaN              0.71   

     encoded_target  artificial  
0               0.0        0.39  
1               0.0        0.43  
2               0.0        0.61  
3               0.0        0.64  
4               0.0        0.74  
..              ...         ...  
144             1.0        0.53  
145             1.0        0.93  
146             1.0        0.51  
147             1.0        0.68  
148             1.0        1.00  

[149 rows x 6 columns]

In [32]:
novo_iris_df['encoded_target'].unique()

array([0. , 0.5, 1. ])

In [33]:
novo_iris_df['petal width (cm)'].unique()

array([0.04,  nan, 0.12, 0.08, 0.  , 0.17, 0.21, 0.54, 0.58, 0.5 , 0.63,
       0.38, 0.42, 0.71, 0.46, 0.67, 1.  , 0.75, 0.83, 0.88, 0.79, 0.96,
       0.92])

In [34]:
novo_iris_df['artificial'].unique()

array([0.39, 0.43, 0.61, 0.64, 0.74, 0.54, 0.53, 0.28, 0.95, 0.05, 0.17,
       0.91, 1.  , 0.35, 0.8 , 0.25, 0.51, 0.93, 0.11, 0.37, 0.4 , 0.22,
       0.68, 0.84, 0.42, 0.31, 0.23, 0.88, 0.67, 0.21, 0.15, 0.18, 0.03,
       0.2 , 0.89, 0.79, 0.44, 0.36, 0.63, 0.7 , 0.24, 0.52, 0.75, 0.56,
       0.49, 0.81, 0.46, 0.76, 0.13, 0.73, 0.08, 0.27, 0.09, 0.97, 0.5 ,
       0.  , 0.07, 0.26, 0.66, 0.01, 0.65, 0.78, 0.12, 0.72, 0.99, 0.86,
       0.71, 0.87, 0.6 , 0.1 , 0.69, 0.3 , 0.33, 0.55, 0.14, 0.57, 0.45,
       0.9 , 0.02, 0.83, 0.19])